### ISSUE TITLE
1.20 support

### ISSUE THREAD

**Issue by ItzSkyReed** [Pixelstormer/better_log4j_config#1]
Please update your mod, it is very useful

**Comment by BigWingBeat** [comment]
Updating the mod to newer versions isn't necessary, as it doesn't directly interact with Minecraft at all. You should be able to just use the same `.jar` for any supported version without any issues, which includes all future versions of Minecraft, at least until Mojang drastically changes how their logging works (Which is very unlikely to actually happen). If the mod doesn't work on a new version for any reason, please do explain the issue so it can be fixed.
