### ISSUE TITLE
Any way to make it load first?

### ISSUE THREAD

**Issue by MeeniMc** [Pixelstormer/better_log4j_config#2]
Is there a way to make this mod load first? Some mods load before it, and thus don't have their output decorated (and of course it is hard to tell which ones, since that's the whole point here :D).

**Comment by BigWingBeat** [comment]
Unfortunately no, Fabric/Quilt explicitly do not have mechanisms to control the order that mods load in, as described at the bottom of [this wiki page](https://fabricmc.net/wiki/documentation:entrypoint). The ideal solution would be for the functionality of this mod to get upstreamed into the mod loaders themselves, but I don't know how likely that is to happen, as I am not at all involved with mod loader development.

**Comment by SettingDust** [comment]
You can load as a dummy language adapter https://github.com/SettingDust/preloading-tricks

**Comment by MeeniMc** [comment]
https://github.com/melontini/better_log4j_config/commit/b52a529d7cff17ef0d88d8b7693504250741b54c
This is pretty cool, thanks @melontini

**Comment by Julienraptor01** [comment]
@Pixelstormer hello, i find this mod extremely useful to debug random people issues in a modpack as it allow to pinpoint what mod is printing stuff, but i've noticed it doesn't load early enough to reconfigure from the start
i then decided to come here take a look at the issues and noticed this issue
could the solution of the message just above by @melontini be upstreamed and released ?

**Comment by zenfyrdev** [comment]
I submitted my changes in this PR: https://github.com/Pixelstormer/better_log4j_config/pull/6. If this falls through, I guess someone could publish my fork themselves.

**Comment by BigWingBeat** [comment]
I'm no longer actively maintaining this mod, but I can merge and release the changes if they work as-is.

**Comment by MeeniMc** [comment]
The PR works as intended
