### ISSUE TITLE
enables debug.log

### ISSUE THREAD

**Issue by inikishev** [Pixelstormer/better_log4j_config#3]
this mod makes the game create debug.log

**Comment by BigWingBeat** [comment]
Yes, the default config includes a logger that outputs to `debug.log`. If you don't want this, you can edit the mod's config file and simply remove that logger. Assuming the config file hasn't been modified at all, you would do this by deleting line 57 in the file, which should be `<AppenderRef ref="DebugFile" level="${sys:fabric.log.debug.level:-debug}"/>` - and you would reenable it by readding that line.

**Comment by inikishev** [comment]
> Yes, the default config includes a logger that outputs to `debug.log`. If you don't want this, you can edit the mod's config file and simply remove that logger. Assuming the config file hasn't been modified at all, you would do this by deleting line 57 in the file, which should be `<AppenderRef ref="DebugFile" level="${sys:fabric.log.debug.level:-debug}"/>` - and you would reenable it by readding that line.

Ok, could it be added to the description? I had this issue before as well and couldn't figure out which mod does that . My main concerns are performance and wearing out ssd as this thing can get big, while it didn't prove to be particularly helpful for debugging mod errrors

**Comment by SlayerTheChikken** [comment]
Yeah the debug file can sometimes get GBs big (even though it's limited by this mod it still writes that much wear on the drive,) I tracked it down to this logging mod which enabled debug.log, some mods will spam the debug with thousands of lines so it's pretty spooky.

https://github.com/gbl/DurabilityViewer/issues/96

**Comment by BigWingBeat** [comment]
I think the best solution would be for `debug.log` to be disabled by default. People who need to enable it would be mod/modpack developers who know what they're doing, and having it enabled by default causes issues for people who don't get any value from it and/or don't know how to disable it.
